# uncompyle6 version 3.8.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: ui\ui_dlgMain.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgMain(object):

    def setupUi(self, dlgMain):
        dlgMain.setObjectName('dlgMain')
        dlgMain.resize(1030, 619)
        font = QtGui.QFont()
        font.setFamily('Arial')
        font.setBold(True)
        font.setWeight(75)
        dlgMain.setFont(font)
        dlgMain.setWindowTitle('')
        dlgMain.setStyleSheet('QWidget {\n    font-family:  "Arial";\n}\n\n#dlgMain {\n    background-color: #EEEEEE;\n}\n\n#labLogo {\n   border-image: url(:/imgs/logo.png);\n}\n\n#btnAdd {\n    font: 15pt;\n}\n\n#btnCov, #btnFormat {\n    background-color: #4283DE;\n    color: #FFFFFF;\n    border-radius: 3px;\n    font-size:15pt;\n}\n\n#btnCov::hover, #btnFormat::hover {\n    background-color:#538DE0;\n}\n\n#btnCov::pressed, #btnFormat::pressed {\n    padding-top: 3px;\n}\n\n#stackRight {\n    border-top: 1px solid #DDDDDD;\n    border-bottom: 1px solid #DDDDDD;\n}\n\n#pageBackground {\n    border-image: url(:imgs/background.png);\n}\n\n#labCenterImg {\n    border-image: url(:/imgs/center.png);\n}\n\n#labCenterText {\n    font: 15pt;\n    color: #8D8B8B;\n    border: 2px dashed  #8D8B8B;\n}\n\n#line {\n    color: #BBBBBB;\n}\n\n#labelUpdateVer{\n    color:blue;\n    border: 0;\n    font-weight:bold;\n    font-size:12px;\n    text-decoration: underline;\n}\n')
        self.centralwidget = QtWidgets.QWidget(dlgMain)
        self.centralwidget.setObjectName('centralwidget')
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName('gridLayout')
        self.layMid = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.layMid.sizePolicy().hasHeightForWidth())
        self.layMid.setSizePolicy(sizePolicy)
        self.layMid.setMinimumSize(QtCore.QSize(0, 0))
        self.layMid.setOrientation(QtCore.Qt.Horizontal)
        self.layMid.setHandleWidth(1)
        self.layMid.setChildrenCollapsible(False)
        self.layMid.setObjectName('layMid')
        self.stackRight = StackRight(self.layMid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackRight.sizePolicy().hasHeightForWidth())
        self.stackRight.setSizePolicy(sizePolicy)
        self.stackRight.setMinimumSize(QtCore.QSize(300, 450))
        self.stackRight.setAcceptDrops(True)
        self.stackRight.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackRight.setLineWidth(1)
        self.stackRight.setObjectName('stackRight')
        self.pageBackground = QtWidgets.QWidget()
        self.pageBackground.setObjectName('pageBackground')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageBackground)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.widCenter = QtWidgets.QWidget(self.pageBackground)
        self.widCenter.setMinimumSize(QtCore.QSize(261, 171))
        self.widCenter.setMaximumSize(QtCore.QSize(261, 171))
        self.widCenter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widCenter.setObjectName('widCenter')
        self.labCenterImg = QtWidgets.QLabel(self.widCenter)
        self.labCenterImg.setGeometry(QtCore.QRect(95, 0, 79, 97))
        self.labCenterImg.setText('')
        self.labCenterImg.setObjectName('labCenterImg')
        self.labCenterText = QtWidgets.QLabel(self.widCenter)
        self.labCenterText.setGeometry(QtCore.QRect(5, 101, 250, 40))
        self.labCenterText.setAlignment(QtCore.Qt.AlignCenter)
        self.labCenterText.setObjectName('labCenterText')
        self.gridLayout_2.addWidget(self.widCenter, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.stackRight.addWidget(self.pageBackground)
        self.pageTable = QtWidgets.QWidget()
        self.pageTable.setObjectName('pageTable')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pageTable)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.tableBook = TableBook(self.pageTable)
        self.tableBook.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableBook.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableBook.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableBook.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableBook.setLineWidth(0)
        self.tableBook.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableBook.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableBook.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableBook.setShowGrid(False)
        self.tableBook.setGridStyle(QtCore.Qt.SolidLine)
        self.tableBook.setObjectName('tableBook')
        self.tableBook.horizontalHeader().setVisible(False)
        self.tableBook.horizontalHeader().setDefaultSectionSize(0)
        self.horizontalLayout_4.addWidget(self.tableBook)
        self.stackRight.addWidget(self.pageTable)
        self.gridLayout.addWidget(self.layMid, 1, 0, 1, 1)
        self.layTop = QtWidgets.QHBoxLayout()
        self.layTop.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layTop.setContentsMargins(12, 5, 12, -1)
        self.layTop.setSpacing(0)
        self.layTop.setObjectName('layTop')
        self.labLogo = QtWidgets.QLabel(self.centralwidget)
        self.labLogo.setMinimumSize(QtCore.QSize(138, 49))
        self.labLogo.setMaximumSize(QtCore.QSize(138, 49))
        self.labLogo.setText('')
        self.labLogo.setObjectName('labLogo')
        self.layTop.addWidget(self.labLogo)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layTop.addItem(spacerItem4)
        self.btnAdd = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 36))
        self.btnAdd.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(':/imgs/add.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setIconSize(QtCore.QSize(19, 19))
        self.btnAdd.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnAdd.setAutoRaise(True)
        self.btnAdd.setObjectName('btnAdd')
        self.layTop.addWidget(self.btnAdd)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layTop.addItem(spacerItem5)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(138, 49))
        self.widget.setMaximumSize(QtCore.QSize(138, 49))
        self.widget.setObjectName('widget')
        self.btnReg = QtWidgets.QToolButton(self.widget)
        self.btnReg.setGeometry(QtCore.QRect(70, 6, 36, 36))
        self.btnReg.setMinimumSize(QtCore.QSize(36, 36))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(':/imgs/register.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReg.setIcon(icon1)
        self.btnReg.setIconSize(QtCore.QSize(12, 20))
        self.btnReg.setAutoRaise(True)
        self.btnReg.setObjectName('btnReg')
        self.btnSettings = QtWidgets.QToolButton(self.widget)
        self.btnSettings.setGeometry(QtCore.QRect(100, 6, 36, 36))
        self.btnSettings.setMinimumSize(QtCore.QSize(36, 36))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(':/imgs/settings.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettings.setIcon(icon2)
        self.btnSettings.setIconSize(QtCore.QSize(20, 20))
        self.btnSettings.setAutoRaise(True)
        self.btnSettings.setObjectName('btnSettings')
        self.layTop.addWidget(self.widget)
        self.gridLayout.addLayout(self.layTop, 0, 0, 1, 1)
        self.layBottom = QtWidgets.QHBoxLayout()
        self.layBottom.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layBottom.setContentsMargins(-1, 0, -1, 0)
        self.layBottom.setSpacing(0)
        self.layBottom.setObjectName('layBottom')
        self.widgetLeft = QtWidgets.QWidget(self.centralwidget)
        self.widgetLeft.setMinimumSize(QtCore.QSize(175, 60))
        self.widgetLeft.setMaximumSize(QtCore.QSize(175, 60))
        self.widgetLeft.setObjectName('widgetLeft')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetLeft)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.labelUpdate = QtWidgets.QLabel(self.widgetLeft)
        self.labelUpdate.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily('Arial')
        font.setBold(True)
        font.setWeight(75)
        self.labelUpdate.setFont(font)
        self.labelUpdate.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelUpdate.setObjectName('labelUpdate')
        self.horizontalLayout.addWidget(self.labelUpdate)
        self.labelUpdateVer = QtWidgets.QToolButton(self.widgetLeft)
        font = QtGui.QFont()
        font.setFamily('Arial')
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelUpdateVer.setFont(font)
        self.labelUpdateVer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelUpdateVer.setObjectName('labelUpdateVer')
        self.horizontalLayout.addWidget(self.labelUpdateVer)
        self.layBottom.addWidget(self.widgetLeft)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layBottom.addItem(spacerItem6)
        self.widCover = QtWidgets.QWidget(self.centralwidget)
        self.widCover.setMinimumSize(QtCore.QSize(550, 60))
        self.widCover.setMaximumSize(QtCore.QSize(550, 60))
        self.widCover.setObjectName('widCover')
        self.btnCov = QtWidgets.QToolButton(self.widCover)
        self.btnCov.setGeometry(QtCore.QRect(170, 7, 170, 38))
        self.btnCov.setMinimumSize(QtCore.QSize(170, 38))
        self.btnCov.setText('')
        self.btnCov.setAutoRepeat(False)
        self.btnCov.setAutoExclusive(False)
        self.btnCov.setAutoRaise(True)
        self.btnCov.setObjectName('btnCov')
        self.btnFormat = QtWidgets.QToolButton(self.widCover)
        self.btnFormat.setGeometry(QtCore.QRect(341, 7, 33, 38))
        self.btnFormat.setMinimumSize(QtCore.QSize(33, 38))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(':/imgs/arrow_down.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFormat.setIcon(icon3)
        self.btnFormat.setAutoRepeat(False)
        self.btnFormat.setAutoExclusive(False)
        self.btnFormat.setAutoRaise(True)
        self.btnFormat.setObjectName('btnFormat')
        self.labCovNum = QtWidgets.QLabel(self.widCover)
        self.labCovNum.setGeometry(QtCore.QRect(415, 8, 120, 30))
        self.labCovNum.setMinimumSize(QtCore.QSize(120, 30))
        self.labCovNum.setMaximumSize(QtCore.QSize(120, 30))
        self.labCovNum.setText('')
        self.labCovNum.setObjectName('labCovNum')
        self.labCovGif = QtWidgets.QLabel(self.widCover)
        self.labCovGif.setGeometry(QtCore.QRect(390, 13, 20, 20))
        self.labCovGif.setMinimumSize(QtCore.QSize(20, 20))
        self.labCovGif.setMaximumSize(QtCore.QSize(20, 20))
        self.labCovGif.setText('')
        self.labCovGif.setObjectName('labCovGif')
        self.layBottom.addWidget(self.widCover)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layBottom.addItem(spacerItem7)
        self.widgetRight = QtWidgets.QWidget(self.centralwidget)
        self.widgetRight.setMinimumSize(QtCore.QSize(175, 60))
        self.widgetRight.setMaximumSize(QtCore.QSize(175, 60))
        self.widgetRight.setObjectName('widgetRight')
        self.btnOut = QtWidgets.QToolButton(self.widgetRight)
        self.btnOut.setGeometry(QtCore.QRect(108, 6, 36, 36))
        self.btnOut.setMinimumSize(QtCore.QSize(32, 32))
        self.btnOut.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(':/imgs/folder.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOut.setIcon(icon4)
        self.btnOut.setIconSize(QtCore.QSize(36, 36))
        self.btnOut.setAutoRaise(True)
        self.btnOut.setArrowType(QtCore.Qt.NoArrow)
        self.btnOut.setObjectName('btnOut')
        self.layBottom.addWidget(self.widgetRight)
        self.gridLayout.addLayout(self.layBottom, 2, 0, 1, 1)
        dlgMain.setCentralWidget(self.centralwidget)
        self.retranslateUi(dlgMain)
        self.stackRight.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dlgMain)
        dlgMain.setTabOrder(self.btnAdd, self.btnCov)
        dlgMain.setTabOrder(self.btnCov, self.btnFormat)
        dlgMain.setTabOrder(self.btnFormat, self.tableBook)

    def retranslateUi(self, dlgMain):
        from settings.settings import tr_ui
        _translate = tr_ui
        self.labCenterText.setText(_translate('dlgMain', 'Drag Drop Books Here'))
        self.btnAdd.setToolTip(_translate('dlgMain', 'Add Audible Books'))
        self.btnAdd.setText(_translate('dlgMain', 'Add'))
        self.btnReg.setToolTip(_translate('dlgMain', 'Register'))
        self.btnReg.setText(_translate('dlgMain', 'Register'))
        self.btnSettings.setToolTip(_translate('dlgMain', 'Settings'))
        self.btnSettings.setText(_translate('dlgMain', 'Settings'))
        self.labelUpdate.setText(_translate('dlgMain', 'Update found:'))
        self.labelUpdateVer.setText(_translate('dlgMain', '1.0.6.68'))
        self.btnCov.setToolTip(_translate('dlgMain', 'Convert Audible Books'))
        self.btnFormat.setToolTip(_translate('dlgMain', 'Select Output Format'))
        self.btnFormat.setText(_translate('dlgMain', 'Select Output Format'))
        self.btnOut.setToolTip(_translate('dlgMain', 'Open output path'))
        self.btnOut.setText(_translate('dlgMain', 'Open output path'))


from ui.tables import StackRight, TableBook
import product_rc