/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'ConsoleApplication1.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct std::_Associated_state<MyData>;
struct std::unique_lock<std::mutex>;
struct std::_Associated_state<MyData>_vtbl;
struct std::_Deleter_base<MyData>;
struct std::_Deleter_base<MyData>_vtbl;

/* 303 */
struct __cppobj __declspec(align(4)) std::_State_manager<MyData>
{
  std::_Associated_state<MyData> *_Assoc_state;
  bool _Get_only_once;
};

/* 357 */
struct __cppobj __declspec(align(4)) std::_Promise<MyData>
{
  std::_State_manager<MyData> _State;
  bool _Future_retrieved;
};

/* 358 */
struct __cppobj std::packaged_task<MyData __cdecl(void)>
{
  std::_Promise<MyData> _MyPromise;
};

/* 244 */
struct MyData
{
  int value;
  float conf;
};

/* 132 */
struct __cppobj std::exception_ptr
{
  void *_Data1;
  void *_Data2;
};

/* 114 */
union std::_Align_type<int,48>
{
  int _Val;
  char _Pad[48];
};

/* 115 */
struct __cppobj std::_Mutex_base
{
  std::_Align_type<int,48> _Mtx_storage;
};

/* 116 */
struct __cppobj std::mutex : std::_Mutex_base
{
};

/* 112 */
union std::_Align_type<int,40>
{
  int _Val;
  char _Pad[40];
};

/* 113 */
struct __cppobj std::condition_variable
{
  std::_Align_type<int,40> _Cnd_storage;
};

/* 298 */
struct __cppobj std::_Associated_state<MyData>
{
  std::_Associated_state<MyData>_vtbl *__vftable /*VFT*/;
  unsigned int _Refs; // 1
  MyData _Result;
  std::exception_ptr _Exception;
  std::mutex _Mtx;
  std::condition_variable _Cond;
  bool _Retrieved; // 0
  int _Ready; // 0 
  bool _Ready_at_thread_exit; //0
  bool _Has_stored_result; //0
  bool _Running; // 0
  std::_Deleter_base<MyData> *_Deleter; //0
};

/* 300 */
struct /*VFT*/ std::_Associated_state<MyData>_vtbl
{
  void (__thiscall *~_Associated_state<MyData>)(std::_Associated_state<MyData> *this);
  void (__thiscall *_Wait)(std::_Associated_state<MyData> *this);
  MyData *(__thiscall *_Get_value)(std::_Associated_state<MyData> *this, bool);
  bool (__thiscall *_Has_deferred_function)(std::_Associated_state<MyData> *this);
  void (__thiscall *_Run_deferred_function)(std::_Associated_state<MyData> *this, std::unique_lock<std::mutex> *);
  void (__thiscall *_Do_notify)(std::_Associated_state<MyData> *this, std::unique_lock<std::mutex> *, bool);
};

/* 301 */
struct __cppobj std::_Deleter_base<MyData>
{
  std::_Deleter_base<MyData>_vtbl *__vftable /*VFT*/;
};

/* 299 */
struct __cppobj __declspec(align(4)) std::unique_lock<std::mutex>
{
  std::mutex *_Pmtx;
  bool _Owns;
};

/* 302 */
struct /*VFT*/ std::_Deleter_base<MyData>_vtbl
{
  void (__thiscall *_Delete)(std::_Deleter_base<MyData> *this, std::_Associated_state<MyData> *);
  void (__thiscall *~_Deleter_base<MyData>)(std::_Deleter_base<MyData> *this);
};

