# uncompyle6 version 3.8.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: ui\ui_dlgReg.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgReg(object):

    def setupUi(self, dlgReg):
        dlgReg.setObjectName('dlgReg')
        dlgReg.resize(745, 485)
        dlgReg.setMinimumSize(QtCore.QSize(745, 485))
        dlgReg.setMaximumSize(QtCore.QSize(745, 485))
        dlgReg.setStyleSheet('\n#dlgReg {\n    background-image: url(:/imgs/regbk.png);\n}\n\n#widCenter {\n    background-color: #FFFFFF;\n}\n\n#labTitle {\n    color: #FFFFFF;\n    font: 11pt;\n}\n\n#line {\n    background-color: #CCCCCC;\n}\n\n#btnReg {\n    background-color: #4283DE;\n    color: #FFFFFF;\n    font: 10pt;\n    border: 1px solid #4283DE;\n    border-radius: 4px;\n}\n\n#btnReg::hover {\n    background-color: #5891E1;\n}\n\n#btnReg::pressed {\n    background-color: #3478D8;\n}\n\n#btnTrial {\n    background-color: #333333;\n    color: #FFFFFF;\n    font: 10pt;\n    border: 1px solid #4283DE;\n    border-radius: 4px;\n}\n\n#btnTrial::hover {\n    background-color: #48494B;\n}\n\n#btnTrial::pressed {\n    background-color: #000000;\n}\n\n#btnClose2 {\n    color: #FFFFFF;\n}\n\n#labProgram {\n    font: bold 13pt;\n}\n\n#btnBuy {\n    background: transparent;\n    color: #FFFFFF;\n    font: bold 11pt;\n    background-image: url(:imgs/buy_normal.png);\n    padding-left: -30px;\n    padding-top: 4px;\n}\n\n#btnBuy::hover {\n    background-image: url(:imgs/buy_hover.png);\n}\n\n#btnBuy::pressed {\n    padding-left: -27px;\n    padding-top: 6px;\n}\n\n#btnClose, #btnClose2 {\n    border: 0;\n}\n')
        self.widCenter = QtWidgets.QWidget(dlgReg)
        self.widCenter.setGeometry(QtCore.QRect(12, 40, 720, 401))
        self.widCenter.setObjectName('widCenter')
        self.labProgram = QtWidgets.QLabel(self.widCenter)
        self.labProgram.setGeometry(QtCore.QRect(430, 40, 271, 31))
        self.labProgram.setObjectName('labProgram')
        self.label_2 = QtWidgets.QLabel(self.widCenter)
        self.label_2.setGeometry(QtCore.QRect(430, 100, 201, 16))
        self.label_2.setObjectName('label_2')
        self.txtMail = QtWidgets.QLineEdit(self.widCenter)
        self.txtMail.setGeometry(QtCore.QRect(430, 130, 251, 22))
        self.txtMail.setObjectName('txtMail')
        self.btnReg = QtWidgets.QPushButton(self.widCenter)
        self.btnReg.setGeometry(QtCore.QRect(595, 180, 86, 27))
        self.btnReg.setCheckable(False)
        self.btnReg.setAutoDefault(False)
        self.btnReg.setDefault(False)
        self.btnReg.setFlat(False)
        self.btnReg.setObjectName('btnReg')
        self.label_4 = QtWidgets.QLabel(self.widCenter)
        self.label_4.setGeometry(QtCore.QRect(432, 250, 251, 71))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName('label_4')
        self.labUrl = QtWidgets.QLabel(self.widCenter)
        self.labUrl.setGeometry(QtCore.QRect(430, 310, 271, 51))
        self.labUrl.setText('')
        self.labUrl.setOpenExternalLinks(True)
        self.labUrl.setObjectName('labUrl')
        self.labInfo = QtWidgets.QLabel(self.widCenter)
        self.labInfo.setGeometry(QtCore.QRect(10, 20, 361, 251))
        self.labInfo.setText('')
        self.labInfo.setWordWrap(True)
        self.labInfo.setObjectName('labInfo')
        self.line = QtWidgets.QFrame(self.widCenter)
        self.line.setGeometry(QtCore.QRect(385, 56, 1, 280))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName('line')
        self.btnBuy = QtWidgets.QPushButton(self.widCenter)
        self.btnBuy.setGeometry(QtCore.QRect(60, 280, 185, 75))
        self.btnBuy.setObjectName('btnBuy')
        self.btnClose = QtWidgets.QPushButton(dlgReg)
        self.btnClose.setGeometry(QtCore.QRect(703, 4, 40, 30))
        self.btnClose.setText('')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(':/imgs/close.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose.setIconSize(QtCore.QSize(40, 30))
        self.btnClose.setFlat(True)
        self.btnClose.setObjectName('btnClose')
        self.labIcon = QtWidgets.QLabel(dlgReg)
        self.labIcon.setGeometry(QtCore.QRect(18, 4, 31, 31))
        self.labIcon.setText('')
        self.labIcon.setPixmap(QtGui.QPixmap(':/imgs/product.ico'))
        self.labIcon.setScaledContents(True)
        self.labIcon.setWordWrap(False)
        self.labIcon.setObjectName('labIcon')
        self.labTitle = QtWidgets.QLabel(dlgReg)
        self.labTitle.setGeometry(QtCore.QRect(55, 9, 471, 21))
        self.labTitle.setText('')
        self.labTitle.setObjectName('labTitle')
        self.btnTrial = QtWidgets.QPushButton(dlgReg)
        self.btnTrial.setGeometry(QtCore.QRect(630, 450, 101, 30))
        self.btnTrial.setObjectName('btnTrial')
        self.btnClose2 = QtWidgets.QPushButton(dlgReg)
        self.btnClose2.setGeometry(QtCore.QRect(554, 458, 71, 20))
        self.btnClose2.setFlat(True)
        self.btnClose2.setObjectName('btnClose2')
        self.retranslateUi(dlgReg)
        QtCore.QMetaObject.connectSlotsByName(dlgReg)
        dlgReg.setTabOrder(self.txtMail, self.btnReg)
        dlgReg.setTabOrder(self.btnReg, self.btnClose2)
        dlgReg.setTabOrder(self.btnClose2, self.btnTrial)
        dlgReg.setTabOrder(self.btnTrial, self.btnClose)
        dlgReg.setTabOrder(self.btnClose, self.btnBuy)

    def retranslateUi(self, dlgReg):
        from settings.settings import tr_ui
        _translate = tr_ui
        dlgReg.setWindowTitle(_translate('dlgReg', 'Register'))
        self.labProgram.setText(_translate('dlgReg', 'Register your program'))
        self.label_2.setText(_translate('dlgReg', 'License Email:'))
        self.btnReg.setText(_translate('dlgReg', 'Register'))
        self.label_4.setText(_translate('dlgReg', 'If you need any assistance with this software, please visit the support page:'))
        self.btnTrial.setText(_translate('dlgReg', 'Free Trial'))
        self.btnClose2.setText(_translate('dlgReg', 'Close'))


import product_rc