# uncompyle6 version 3.8.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: ui\ui_dlgSettings.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgSettings(object):

    def setupUi(self, dlgSettings):
        dlgSettings.setObjectName('dlgSettings')
        dlgSettings.resize(760, 500)
        dlgSettings.setMinimumSize(QtCore.QSize(760, 500))
        dlgSettings.setMaximumSize(QtCore.QSize(760, 500))
        dlgSettings.setStyleSheet('#dlgSettings {\n    background-color: #EEEEEE;\n}\n\n#widTool {\n    background-color: #4D4D4D;\n}\n\n#widNavigate {\n    background-color: #676767;\n}\n\n#stackRoot {\n    background-color: #FFFFFF;\n}\n\n#labTitle {\n    color: #FFFFFF;\n}\n\n#btnSettings, #btnHelp {\n    color: #FFFFFF;\n    font: bold 10pt;\n}\n\n#lineSettings, #lineHelp {\n    background-color: #CCCCCC;\n}\n\n#line1, #line2 {\n    background-color: #666666;\n}\n\n#cline1, #cline2, #cline3, #cline4, #cline5 {\n    background-color: #CCCCCC;\n}\n\n#btnOutDefault {\n    color: #0000FF;\n    text-decoration: underline;\n    border: 0;\n    text-align: left;\n}\n\n#labOut {\n    font-size: 11pt;\n    font-weight: 600;\n}\n\n#btnOutPath, #btnOutOK, #btnLangOK, #btnDeRegister {\n    background-color: #4283DE;\n    color: #FFFFFF;\n    border: 1px solid #4283DE;\n    border-radius: 2px;\n}\n\n#btnOutPath::hover, #btnOutOK::hover,  #btnLangOK::hover,  #btnDeRegister::hover {\n    background-color: #5891E1;\n}\n\n#btnOutPath::pressed, #btnOutOK::pressed, #btnLangOK::pressed, #btnDeRegister::pressed {\n    background-color: #3478D8;\n}\n')
        self.widTool = QtWidgets.QWidget(dlgSettings)
        self.widTool.setGeometry(QtCore.QRect(0, 0, 760, 45))
        self.widTool.setObjectName('widTool')
        self.labTitle = QtWidgets.QLabel(self.widTool)
        self.labTitle.setGeometry(QtCore.QRect(60, 10, 521, 25))
        self.labTitle.setText('')
        self.labTitle.setObjectName('labTitle')
        self.labTitleIcon = QtWidgets.QLabel(self.widTool)
        self.labTitleIcon.setGeometry(QtCore.QRect(19, 8, 31, 31))
        self.labTitleIcon.setText('')
        self.labTitleIcon.setPixmap(QtGui.QPixmap(':/imgs/product.ico'))
        self.labTitleIcon.setScaledContents(True)
        self.labTitleIcon.setObjectName('labTitleIcon')
        self.widNavigate = QtWidgets.QWidget(dlgSettings)
        self.widNavigate.setGeometry(QtCore.QRect(0, 44, 105, 456))
        self.widNavigate.setObjectName('widNavigate')
        self.btnSettings = QtWidgets.QToolButton(self.widNavigate)
        self.btnSettings.setGeometry(QtCore.QRect(0, 0, 104, 80))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(':/imgs/settings2.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettings.setIcon(icon)
        self.btnSettings.setIconSize(QtCore.QSize(38, 48))
        self.btnSettings.setCheckable(False)
        self.btnSettings.setAutoExclusive(False)
        self.btnSettings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnSettings.setAutoRaise(True)
        self.btnSettings.setObjectName('btnSettings')
        self.btnHelp = QtWidgets.QToolButton(self.widNavigate)
        self.btnHelp.setGeometry(QtCore.QRect(0, 81, 104, 80))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(':/imgs/help.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon1)
        self.btnHelp.setIconSize(QtCore.QSize(38, 48))
        self.btnHelp.setCheckable(False)
        self.btnHelp.setAutoExclusive(False)
        self.btnHelp.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnHelp.setAutoRaise(True)
        self.btnHelp.setObjectName('btnHelp')
        self.line1 = QtWidgets.QFrame(self.widNavigate)
        self.line1.setGeometry(QtCore.QRect(1, 80, 104, 1))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName('line1')
        self.line2 = QtWidgets.QFrame(self.widNavigate)
        self.line2.setGeometry(QtCore.QRect(1, 161, 104, 1))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName('line2')
        self.stackRoot = QtWidgets.QStackedWidget(dlgSettings)
        self.stackRoot.setGeometry(QtCore.QRect(105, 44, 655, 411))
        self.stackRoot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackRoot.setLineWidth(0)
        self.stackRoot.setObjectName('stackRoot')
        self.pageSettings = QtWidgets.QWidget()
        self.pageSettings.setObjectName('pageSettings')
        self.cline1 = QtWidgets.QFrame(self.pageSettings)
        self.cline1.setGeometry(QtCore.QRect(0, 32, 135, 1))
        self.cline1.setFrameShape(QtWidgets.QFrame.HLine)
        self.cline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cline1.setObjectName('cline1')
        self.cline2 = QtWidgets.QFrame(self.pageSettings)
        self.cline2.setGeometry(QtCore.QRect(0, 65, 135, 1))
        self.cline2.setFrameShape(QtWidgets.QFrame.HLine)
        self.cline2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cline2.setObjectName('cline2')
        self.btnLang = QtWidgets.QPushButton(self.pageSettings)
        self.btnLang.setGeometry(QtCore.QRect(0, 0, 135, 32))
        self.btnLang.setCheckable(False)
        self.btnLang.setAutoExclusive(False)
        self.btnLang.setFlat(False)
        self.btnLang.setObjectName('btnLang')
        self.btnOutput = QtWidgets.QPushButton(self.pageSettings)
        self.btnOutput.setGeometry(QtCore.QRect(0, 33, 135, 32))
        self.btnOutput.setCheckable(False)
        self.btnOutput.setAutoExclusive(False)
        self.btnOutput.setFlat(False)
        self.btnOutput.setObjectName('btnOutput')
        self.lineSettings = QtWidgets.QFrame(self.pageSettings)
        self.lineSettings.setGeometry(QtCore.QRect(136, 0, 1, 415))
        self.lineSettings.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSettings.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSettings.setObjectName('lineSettings')
        self.stackSettings = QtWidgets.QStackedWidget(self.pageSettings)
        self.stackSettings.setGeometry(QtCore.QRect(142, 8, 511, 401))
        self.stackSettings.setObjectName('stackSettings')
        self.pageLang = QtWidgets.QWidget()
        self.pageLang.setObjectName('pageLang')
        self.label_3 = QtWidgets.QLabel(self.pageLang)
        self.label_3.setGeometry(QtCore.QRect(10, 42, 171, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName('label_3')
        self.cboxLang = QtWidgets.QComboBox(self.pageLang)
        self.cboxLang.setGeometry(QtCore.QRect(193, 50, 181, 25))
        self.cboxLang.setEditable(False)
        self.cboxLang.setObjectName('cboxLang')
        self.btnLangOK = QtWidgets.QPushButton(self.pageLang)
        self.btnLangOK.setGeometry(QtCore.QRect(390, 50, 75, 25))
        self.btnLangOK.setObjectName('btnLangOK')
        self.stackSettings.addWidget(self.pageLang)
        self.pageOutput = QtWidgets.QWidget()
        self.pageOutput.setObjectName('pageOutput')
        self.btnOutOK = QtWidgets.QPushButton(self.pageOutput)
        self.btnOutOK.setGeometry(QtCore.QRect(402, 149, 75, 25))
        self.btnOutOK.setObjectName('btnOutOK')
        self.labOut = QtWidgets.QLabel(self.pageOutput)
        self.labOut.setGeometry(QtCore.QRect(85, 10, 301, 31))
        self.labOut.setAlignment(QtCore.Qt.AlignCenter)
        self.labOut.setWordWrap(False)
        self.labOut.setObjectName('labOut')
        self.groupBox_6 = QtWidgets.QGroupBox(self.pageOutput)
        self.groupBox_6.setGeometry(QtCore.QRect(27, 46, 461, 91))
        self.groupBox_6.setObjectName('groupBox_6')
        self.txtOutPath = QtWidgets.QLineEdit(self.groupBox_6)
        self.txtOutPath.setGeometry(QtCore.QRect(10, 27, 351, 25))
        self.txtOutPath.setReadOnly(True)
        self.txtOutPath.setObjectName('txtOutPath')
        self.btnOutPath = QtWidgets.QPushButton(self.groupBox_6)
        self.btnOutPath.setGeometry(QtCore.QRect(373, 27, 75, 25))
        self.btnOutPath.setObjectName('btnOutPath')
        self.btnOutDefault = QtWidgets.QPushButton(self.groupBox_6)
        self.btnOutDefault.setGeometry(QtCore.QRect(13, 56, 241, 30))
        self.btnOutDefault.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnOutDefault.setFlat(False)
        self.btnOutDefault.setObjectName('btnOutDefault')
        self.stackSettings.addWidget(self.pageOutput)
        self.stackRoot.addWidget(self.pageSettings)
        self.pageHelp = QtWidgets.QWidget()
        self.pageHelp.setObjectName('pageHelp')
        self.cline5 = QtWidgets.QFrame(self.pageHelp)
        self.cline5.setGeometry(QtCore.QRect(-1, 97, 135, 1))
        self.cline5.setFrameShape(QtWidgets.QFrame.HLine)
        self.cline5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cline5.setObjectName('cline5')
        self.btnLicenseManager = QtWidgets.QPushButton(self.pageHelp)
        self.btnLicenseManager.setGeometry(QtCore.QRect(-1, -1, 135, 32))
        self.btnLicenseManager.setCheckable(False)
        self.btnLicenseManager.setAutoExclusive(False)
        self.btnLicenseManager.setFlat(False)
        self.btnLicenseManager.setObjectName('btnLicenseManager')
        self.cline4 = QtWidgets.QFrame(self.pageHelp)
        self.cline4.setGeometry(QtCore.QRect(-1, 64, 135, 1))
        self.cline4.setFrameShape(QtWidgets.QFrame.HLine)
        self.cline4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cline4.setObjectName('cline4')
        self.btnAbout = QtWidgets.QPushButton(self.pageHelp)
        self.btnAbout.setGeometry(QtCore.QRect(-1, 65, 135, 32))
        self.btnAbout.setCheckable(False)
        self.btnAbout.setAutoExclusive(False)
        self.btnAbout.setFlat(False)
        self.btnAbout.setObjectName('btnAbout')
        self.lineHelp = QtWidgets.QFrame(self.pageHelp)
        self.lineHelp.setGeometry(QtCore.QRect(135, -1, 1, 415))
        self.lineHelp.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineHelp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineHelp.setObjectName('lineHelp')
        self.cline3 = QtWidgets.QFrame(self.pageHelp)
        self.cline3.setGeometry(QtCore.QRect(-1, 31, 135, 1))
        self.cline3.setFrameShape(QtWidgets.QFrame.HLine)
        self.cline3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cline3.setObjectName('cline3')
        self.btnHelpHelp = QtWidgets.QPushButton(self.pageHelp)
        self.btnHelpHelp.setGeometry(QtCore.QRect(-1, 32, 135, 32))
        self.btnHelpHelp.setCheckable(False)
        self.btnHelpHelp.setAutoExclusive(False)
        self.btnHelpHelp.setFlat(False)
        self.btnHelpHelp.setObjectName('btnHelpHelp')
        self.stackHelp = QtWidgets.QStackedWidget(self.pageHelp)
        self.stackHelp.setGeometry(QtCore.QRect(139, 6, 511, 401))
        self.stackHelp.setObjectName('stackHelp')
        self.pageLicenseManager = QtWidgets.QWidget()
        self.pageLicenseManager.setObjectName('pageLicenseManager')
        self.groupBoxDeRegister = QtWidgets.QGroupBox(self.pageLicenseManager)
        self.groupBoxDeRegister.setGeometry(QtCore.QRect(10, 30, 491, 181))
        self.groupBoxDeRegister.setObjectName('groupBoxDeRegister')
        self.labelDeregisterInfo = QtWidgets.QLabel(self.groupBoxDeRegister)
        self.labelDeregisterInfo.setGeometry(QtCore.QRect(20, 30, 461, 81))
        self.labelDeregisterInfo.setText('')
        self.labelDeregisterInfo.setObjectName('labelDeregisterInfo')
        self.btnDeRegister = QtWidgets.QPushButton(self.groupBoxDeRegister)
        self.btnDeRegister.setGeometry(QtCore.QRect(360, 130, 101, 31))
        self.btnDeRegister.setObjectName('btnDeRegister')
        self.stackHelp.addWidget(self.pageLicenseManager)
        self.pageHelpHelp = QtWidgets.QWidget()
        self.pageHelpHelp.setObjectName('pageHelpHelp')
        self.labHelp = QtWidgets.QLabel(self.pageHelpHelp)
        self.labHelp.setGeometry(QtCore.QRect(40, 40, 431, 221))
        self.labHelp.setText('')
        self.labHelp.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.labHelp.setOpenExternalLinks(True)
        self.labHelp.setObjectName('labHelp')
        self.stackHelp.addWidget(self.pageHelpHelp)
        self.pageAbout = QtWidgets.QWidget()
        self.pageAbout.setObjectName('pageAbout')
        self.labAbout = QtWidgets.QLabel(self.pageAbout)
        self.labAbout.setGeometry(QtCore.QRect(40, 20, 441, 181))
        self.labAbout.setText('')
        self.labAbout.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.labAbout.setWordWrap(True)
        self.labAbout.setOpenExternalLinks(True)
        self.labAbout.setObjectName('labAbout')
        self.labAbout2 = QtWidgets.QLabel(self.pageAbout)
        self.labAbout2.setGeometry(QtCore.QRect(100, 230, 351, 141))
        self.labAbout2.setText('')
        self.labAbout2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.labAbout2.setWordWrap(True)
        self.labAbout2.setOpenExternalLinks(True)
        self.labAbout2.setObjectName('labAbout2')
        self.stackHelp.addWidget(self.pageAbout)
        self.stackRoot.addWidget(self.pageHelp)
        self.retranslateUi(dlgSettings)
        self.stackRoot.setCurrentIndex(1)
        self.stackSettings.setCurrentIndex(0)
        self.stackHelp.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlgSettings)
        dlgSettings.setTabOrder(self.btnSettings, self.btnHelp)
        dlgSettings.setTabOrder(self.btnHelp, self.btnLang)
        dlgSettings.setTabOrder(self.btnLang, self.btnOutput)
        dlgSettings.setTabOrder(self.btnOutput, self.cboxLang)
        dlgSettings.setTabOrder(self.cboxLang, self.btnLangOK)
        dlgSettings.setTabOrder(self.btnLangOK, self.txtOutPath)
        dlgSettings.setTabOrder(self.txtOutPath, self.btnOutPath)
        dlgSettings.setTabOrder(self.btnOutPath, self.btnOutDefault)
        dlgSettings.setTabOrder(self.btnOutDefault, self.btnOutOK)
        dlgSettings.setTabOrder(self.btnOutOK, self.btnHelpHelp)
        dlgSettings.setTabOrder(self.btnHelpHelp, self.btnLicenseManager)
        dlgSettings.setTabOrder(self.btnLicenseManager, self.btnAbout)

    def retranslateUi(self, dlgSettings):
        from settings.settings import tr_ui
        _translate = tr_ui
        dlgSettings.setWindowTitle(_translate('dlgSettings', 'Dialog'))
        self.btnSettings.setText(_translate('dlgSettings', 'Settings'))
        self.btnHelp.setText(_translate('dlgSettings', 'Help'))
        self.btnLang.setText(_translate('dlgSettings', 'Language    >  '))
        self.btnOutput.setText(_translate('dlgSettings', 'Output    >  '))
        self.label_3.setText(_translate('dlgSettings', 'User Interface Language:'))
        self.btnLangOK.setText(_translate('dlgSettings', 'OK'))
        self.btnOutOK.setText(_translate('dlgSettings', 'OK'))
        self.labOut.setText(_translate('dlgSettings', 'Output Path'))
        self.groupBox_6.setTitle(_translate('dlgSettings', 'Source location'))
        self.btnOutPath.setText(_translate('dlgSettings', 'Browse'))
        self.btnOutDefault.setText(_translate('dlgSettings', 'Set to default directory'))
        self.btnLicenseManager.setText(_translate('dlgSettings', 'License Manager    >  '))
        self.btnAbout.setText(_translate('dlgSettings', 'About    >  '))
        self.btnHelpHelp.setText(_translate('dlgSettings', 'Help    >  '))
        self.groupBoxDeRegister.setTitle(_translate('dlgSettings', 'De-register'))
        self.btnDeRegister.setText(_translate('dlgSettings', 'De-register'))


import product_rc