# uncompyle6 version 3.8.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: ui\ui_dlgOption.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgOption(object):

    def setupUi(self, dlgOption):
        dlgOption.setObjectName('dlgOption')
        dlgOption.resize(742, 493)
        dlgOption.setStyleSheet('#btnOK {\n    background-color: #4283DE;\n    color: #FFFFFF;\n    border: 1px solid #4283DE;\n    border-radius: 2px;\n}\n\n#btnOK::hover {\n    background-color: #5891E1;\n}\n\n#btnOK::pressed {\n    background-color: #3478D8;\n}')
        self.gridLayout = QtWidgets.QGridLayout(dlgOption)
        self.gridLayout.setObjectName('gridLayout')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 20, 5)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(dlgOption)
        self.btnOK.setObjectName('btnOK')
        self.horizontalLayout_3.addWidget(self.btnOK)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.tabOption = QtWidgets.QTabWidget(dlgOption)
        self.tabOption.setObjectName('tabOption')
        self.pageSplit = QtWidgets.QWidget()
        self.pageSplit.setObjectName('pageSplit')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageSplit)
        self.verticalLayout.setContentsMargins(0, 20, 0, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName('verticalLayout')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.radioBtnNoSplit = QtWidgets.QRadioButton(self.pageSplit)
        self.radioBtnNoSplit.setObjectName('radioBtnNoSplit')
        self.horizontalLayout_5.addWidget(self.radioBtnNoSplit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.radioBtnSplitMinutes = QtWidgets.QRadioButton(self.pageSplit)
        self.radioBtnSplitMinutes.setObjectName('radioBtnSplitMinutes')
        self.horizontalLayout_2.addWidget(self.radioBtnSplitMinutes)
        self.spinBoxMinutes = QtWidgets.QSpinBox(self.pageSplit)
        self.spinBoxMinutes.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxMinutes.setMinimum(1)
        self.spinBoxMinutes.setMaximum(999999)
        self.spinBoxMinutes.setObjectName('spinBoxMinutes')
        self.horizontalLayout_2.addWidget(self.spinBoxMinutes)
        self.labelMinutes = QtWidgets.QLabel(self.pageSplit)
        self.labelMinutes.setObjectName('labelMinutes')
        self.horizontalLayout_2.addWidget(self.labelMinutes)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.radioBtnSplitFiles = QtWidgets.QRadioButton(self.pageSplit)
        self.radioBtnSplitFiles.setObjectName('radioBtnSplitFiles')
        self.horizontalLayout.addWidget(self.radioBtnSplitFiles)
        self.spinBoxFiles = QtWidgets.QSpinBox(self.pageSplit)
        self.spinBoxFiles.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxFiles.setMinimum(1)
        self.spinBoxFiles.setMaximum(200)
        self.spinBoxFiles.setObjectName('spinBoxFiles')
        self.horizontalLayout.addWidget(self.spinBoxFiles)
        self.labelSA = QtWidgets.QLabel(self.pageSplit)
        self.labelSA.setObjectName('labelSA')
        self.horizontalLayout.addWidget(self.labelSA)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName('horizontalLayout_6')
        self.radioBtnSplitChapters = QtWidgets.QRadioButton(self.pageSplit)
        self.radioBtnSplitChapters.setObjectName('radioBtnSplitChapters')
        self.horizontalLayout_6.addWidget(self.radioBtnSplitChapters)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.checkBoxApplyToAll = QtWidgets.QCheckBox(self.pageSplit)
        self.checkBoxApplyToAll.setObjectName('checkBoxApplyToAll')
        self.verticalLayout.addWidget(self.checkBoxApplyToAll)
        self.tabOption.addTab(self.pageSplit, '')
        self.pageMeta = QtWidgets.QWidget()
        self.pageMeta.setObjectName('pageMeta')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pageMeta)
        self.horizontalLayout_4.setContentsMargins(0, 0, 30, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 20, -1, 20)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.label = QtWidgets.QLabel(self.pageMeta)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName('label')
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.txtTitle = QtWidgets.QLineEdit(self.pageMeta)
        self.txtTitle.setMinimumSize(QtCore.QSize(0, 25))
        self.txtTitle.setObjectName('txtTitle')
        self.gridLayout_2.addWidget(self.txtTitle, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.pageMeta)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName('label_2')
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtAlbum = QtWidgets.QLineEdit(self.pageMeta)
        self.txtAlbum.setMinimumSize(QtCore.QSize(0, 25))
        self.txtAlbum.setObjectName('txtAlbum')
        self.gridLayout_2.addWidget(self.txtAlbum, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.pageMeta)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName('label_3')
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtArtist = QtWidgets.QLineEdit(self.pageMeta)
        self.txtArtist.setMinimumSize(QtCore.QSize(0, 25))
        self.txtArtist.setObjectName('txtArtist')
        self.gridLayout_2.addWidget(self.txtArtist, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.pageMeta)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName('label_4')
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.txtCopyright = QtWidgets.QLineEdit(self.pageMeta)
        self.txtCopyright.setMinimumSize(QtCore.QSize(0, 25))
        self.txtCopyright.setObjectName('txtCopyright')
        self.gridLayout_2.addWidget(self.txtCopyright, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.pageMeta)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName('label_5')
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.txtYear = QtWidgets.QLineEdit(self.pageMeta)
        self.txtYear.setMinimumSize(QtCore.QSize(0, 25))
        self.txtYear.setObjectName('txtYear')
        self.gridLayout_2.addWidget(self.txtYear, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.pageMeta)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName('label_6')
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboxGenre = QtWidgets.QComboBox(self.pageMeta)
        self.comboxGenre.setMinimumSize(QtCore.QSize(0, 25))
        self.comboxGenre.setObjectName('comboxGenre')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.comboxGenre.addItem('')
        self.gridLayout_2.addWidget(self.comboxGenre, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pageMeta)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName('label_7')
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.txtComments = QtWidgets.QPlainTextEdit(self.pageMeta)
        self.txtComments.setObjectName('txtComments')
        self.gridLayout_2.addWidget(self.txtComments, 6, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.btnCover = QtWidgets.QPushButton(self.pageMeta)
        self.btnCover.setMinimumSize(QtCore.QSize(200, 250))
        self.btnCover.setMaximumSize(QtCore.QSize(200, 250))
        self.btnCover.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCover.setText('')
        self.btnCover.setAutoDefault(True)
        self.btnCover.setFlat(True)
        self.btnCover.setObjectName('btnCover')
        self.horizontalLayout_4.addWidget(self.btnCover)
        self.tabOption.addTab(self.pageMeta, '')
        self.gridLayout.addWidget(self.tabOption, 0, 0, 1, 1)
        self.retranslateUi(dlgOption)
        self.tabOption.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(dlgOption)

    def retranslateUi(self, dlgOption):
        from settings.settings import tr_ui
        _translate = tr_ui
        dlgOption.setWindowTitle(_translate('dlgOption', 'Dialog'))
        self.btnOK.setText(_translate('dlgOption', 'OK'))
        self.radioBtnNoSplit.setText(_translate('dlgOption', 'No split'))
        self.radioBtnSplitMinutes.setText(_translate('dlgOption', 'Split every'))
        self.labelMinutes.setText(_translate('dlgOption', 'minute(s)'))
        self.radioBtnSplitFiles.setText(_translate('dlgOption', 'Split into'))
        self.labelSA.setText(_translate('dlgOption', 'segments averagely'))
        self.radioBtnSplitChapters.setText(_translate('dlgOption', 'Split by chapters'))
        self.checkBoxApplyToAll.setText(_translate('dlgOption', 'Apply to all'))
        self.tabOption.setTabText(self.tabOption.indexOf(self.pageSplit), _translate('dlgOption', 'Split'))
        self.label.setText(_translate('dlgOption', 'Title:'))
        self.label_2.setText(_translate('dlgOption', 'Album:'))
        self.label_3.setText(_translate('dlgOption', 'Artist:'))
        self.label_4.setText(_translate('dlgOption', 'Copyright:'))
        self.label_5.setText(_translate('dlgOption', 'Year:'))
        self.label_6.setText(_translate('dlgOption', 'Genre:'))
        self.comboxGenre.setItemText(0, _translate('dlgOption', 'Audiobook'))
        self.comboxGenre.setItemText(1, _translate('dlgOption', 'Altermative'))
        self.comboxGenre.setItemText(2, _translate('dlgOption', 'Blues'))
        self.comboxGenre.setItemText(3, _translate('dlgOption', 'Books&Spoken'))
        self.comboxGenre.setItemText(4, _translate('dlgOption', "Children's Music"))
        self.comboxGenre.setItemText(5, _translate('dlgOption', 'Classical'))
        self.comboxGenre.setItemText(6, _translate('dlgOption', 'Comedy'))
        self.comboxGenre.setItemText(7, _translate('dlgOption', 'Dance'))
        self.comboxGenre.setItemText(8, _translate('dlgOption', 'Electronic'))
        self.comboxGenre.setItemText(9, _translate('dlgOption', 'Folk'))
        self.comboxGenre.setItemText(10, _translate('dlgOption', 'Hip Hop/Rap'))
        self.comboxGenre.setItemText(11, _translate('dlgOption', 'Holiday'))
        self.comboxGenre.setItemText(12, _translate('dlgOption', 'House'))
        self.comboxGenre.setItemText(13, _translate('dlgOption', 'Industrial'))
        self.comboxGenre.setItemText(14, _translate('dlgOption', 'Jazz'))
        self.comboxGenre.setItemText(15, _translate('dlgOption', 'Metal'))
        self.comboxGenre.setItemText(16, _translate('dlgOption', 'Pop'))
        self.comboxGenre.setItemText(17, _translate('dlgOption', 'Podcast'))
        self.comboxGenre.setItemText(18, _translate('dlgOption', 'R&B'))
        self.comboxGenre.setItemText(19, _translate('dlgOption', 'Religious'))
        self.comboxGenre.setItemText(20, _translate('dlgOption', 'Rock'))
        self.comboxGenre.setItemText(21, _translate('dlgOption', 'Trance'))
        self.label_7.setText(_translate('dlgOption', 'Comments:'))
        self.btnCover.setToolTip(_translate('dlgOption', 'Replace the cover'))
        self.tabOption.setTabText(self.tabOption.indexOf(self.pageMeta), _translate('dlgOption', 'Meta'))