#ifndef _PROJECT_VERSION_H_
#define _PROJECT_VERSION_H_
#ifndef PROJECT_VERSION_SYSTEM_FILE
#define PROJECT_VERSION_SYSTEM_FILE         1,0,2,127
#endif
#ifndef PROJECT_VERSION_SYSTEM_PRODUCT
#define PROJECT_VERSION_SYSTEM_PRODUCT      1,0,2,127
#endif
#ifndef PROJECT_VERSION_DISPLAY_FILE
#define PROJECT_VERSION_DISPLAY_FILE        "1,0,2,127-d-9b672d2"
#endif
#ifndef PROJECT_VERSION_DISPLAY_PRODUCT
#define PROJECT_VERSION_DISPLAY_PRODUCT     "1,0,2,127-d-9b672d2"
#endif
#ifndef PROJECT_OWNER_COMPANY_NAME
#define PROJECT_OWNER_COMPANY_NAME          "Tenorshare CO.,Ltd."
#endif
#ifndef PROJECT_OWNER_PRODUCT_NAME
#define PROJECT_OWNER_PRODUCT_NAME          "Tenorshare Product Library"
#endif
#ifndef PROJECT_OWNER_LEGAL_COPYRIGHT
#define PROJECT_OWNER_LEGAL_COPYRIGHT       "Copyright (C) 2007-2021 Tenorshare CO.,Ltd."
#endif
#endif
