# uncompyle6 version 3.8.0
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: cryptography\hazmat\primitives\kdf\__init__.py
import abc

class KeyDerivationFunction(metaclass=abc.ABCMeta):

    @abc.abstractmethod
    def derive(self, key_material: bytes) -> bytes:
        """
        Deterministically generates and returns a new key based on the existing
        key material.
        """
        pass

    @abc.abstractmethod
    def verify(self, key_material: bytes, expected_key: bytes) -> None:
        """
        Checks whether the key generated by the key material matches the
        expected derived key. Raises an exception if they do not match.
        """
        pass